#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skynet_web.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Nhadat")]
	public partial class NhadatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDuAN1(DuAN1 instance);
    partial void UpdateDuAN1(DuAN1 instance);
    partial void DeleteDuAN1(DuAN1 instance);
    partial void InsertHouse(House instance);
    partial void UpdateHouse(House instance);
    partial void DeleteHouse(House instance);
    partial void InsertImageduan(Imageduan instance);
    partial void UpdateImageduan(Imageduan instance);
    partial void DeleteImageduan(Imageduan instance);
    partial void InsertImagehouse(Imagehouse instance);
    partial void UpdateImagehouse(Imagehouse instance);
    partial void DeleteImagehouse(Imagehouse instance);
    partial void InsertNhadautu(Nhadautu instance);
    partial void UpdateNhadautu(Nhadautu instance);
    partial void DeleteNhadautu(Nhadautu instance);
    partial void InsertTaikhoan(Taikhoan instance);
    partial void UpdateTaikhoan(Taikhoan instance);
    partial void DeleteTaikhoan(Taikhoan instance);
    partial void InsertTintuc(Tintuc instance);
    partial void UpdateTintuc(Tintuc instance);
    partial void DeleteTintuc(Tintuc instance);
    #endregion
		
		public NhadatDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["NhadatConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NhadatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhadatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhadatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NhadatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DuAN1> DuAN1s
		{
			get
			{
				return this.GetTable<DuAN1>();
			}
		}
		
		public System.Data.Linq.Table<House> Houses
		{
			get
			{
				return this.GetTable<House>();
			}
		}
		
		public System.Data.Linq.Table<Imageduan> Imageduans
		{
			get
			{
				return this.GetTable<Imageduan>();
			}
		}
		
		public System.Data.Linq.Table<Imagehouse> Imagehouses
		{
			get
			{
				return this.GetTable<Imagehouse>();
			}
		}
		
		public System.Data.Linq.Table<Nhadautu> Nhadautus
		{
			get
			{
				return this.GetTable<Nhadautu>();
			}
		}
		
		public System.Data.Linq.Table<Taikhoan> Taikhoans
		{
			get
			{
				return this.GetTable<Taikhoan>();
			}
		}
		
		public System.Data.Linq.Table<Tintuc> Tintucs
		{
			get
			{
				return this.GetTable<Tintuc>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAN1")]
	public partial class DuAN1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDDuAn;
		
		private string _khoiduan;
		
		private System.Nullable<int> _sonha;
		
		private System.Nullable<int> _House;
		
		private string _mota;
		
		private System.Nullable<int> _IDnhadautu;
		
		private string _vitri;
		
		private string _Tenduan;
		
		private System.Nullable<int> _Giaban;
		
		private System.Nullable<int> _Giathue;
		
		private EntitySet<House> _Houses;
		
		private EntitySet<Imageduan> _Imageduans;
		
		private EntityRef<Nhadautu> _Nhadautu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDuAnChanging(int value);
    partial void OnIDDuAnChanged();
    partial void OnkhoiduanChanging(string value);
    partial void OnkhoiduanChanged();
    partial void OnsonhaChanging(System.Nullable<int> value);
    partial void OnsonhaChanged();
    partial void OnHouseChanging(System.Nullable<int> value);
    partial void OnHouseChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnIDnhadautuChanging(System.Nullable<int> value);
    partial void OnIDnhadautuChanged();
    partial void OnvitriChanging(string value);
    partial void OnvitriChanged();
    partial void OnTenduanChanging(string value);
    partial void OnTenduanChanged();
    partial void OnGiabanChanging(System.Nullable<int> value);
    partial void OnGiabanChanged();
    partial void OnGiathueChanging(System.Nullable<int> value);
    partial void OnGiathueChanged();
    #endregion
		
		public DuAN1()
		{
			this._Houses = new EntitySet<House>(new Action<House>(this.attach_Houses), new Action<House>(this.detach_Houses));
			this._Imageduans = new EntitySet<Imageduan>(new Action<Imageduan>(this.attach_Imageduans), new Action<Imageduan>(this.detach_Imageduans));
			this._Nhadautu = default(EntityRef<Nhadautu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDuAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDDuAn
		{
			get
			{
				return this._IDDuAn;
			}
			set
			{
				if ((this._IDDuAn != value))
				{
					this.OnIDDuAnChanging(value);
					this.SendPropertyChanging();
					this._IDDuAn = value;
					this.SendPropertyChanged("IDDuAn");
					this.OnIDDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khoiduan", DbType="NVarChar(50)")]
		public string khoiduan
		{
			get
			{
				return this._khoiduan;
			}
			set
			{
				if ((this._khoiduan != value))
				{
					this.OnkhoiduanChanging(value);
					this.SendPropertyChanging();
					this._khoiduan = value;
					this.SendPropertyChanged("khoiduan");
					this.OnkhoiduanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonha", DbType="Int")]
		public System.Nullable<int> sonha
		{
			get
			{
				return this._sonha;
			}
			set
			{
				if ((this._sonha != value))
				{
					this.OnsonhaChanging(value);
					this.SendPropertyChanging();
					this._sonha = value;
					this.SendPropertyChanged("sonha");
					this.OnsonhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_House", DbType="Int")]
		public System.Nullable<int> House
		{
			get
			{
				return this._House;
			}
			set
			{
				if ((this._House != value))
				{
					this.OnHouseChanging(value);
					this.SendPropertyChanging();
					this._House = value;
					this.SendPropertyChanged("House");
					this.OnHouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(3000)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDnhadautu", DbType="Int")]
		public System.Nullable<int> IDnhadautu
		{
			get
			{
				return this._IDnhadautu;
			}
			set
			{
				if ((this._IDnhadautu != value))
				{
					if (this._Nhadautu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDnhadautuChanging(value);
					this.SendPropertyChanging();
					this._IDnhadautu = value;
					this.SendPropertyChanged("IDnhadautu");
					this.OnIDnhadautuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitri", DbType="NVarChar(50)")]
		public string vitri
		{
			get
			{
				return this._vitri;
			}
			set
			{
				if ((this._vitri != value))
				{
					this.OnvitriChanging(value);
					this.SendPropertyChanging();
					this._vitri = value;
					this.SendPropertyChanged("vitri");
					this.OnvitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenduan", DbType="NVarChar(50)")]
		public string Tenduan
		{
			get
			{
				return this._Tenduan;
			}
			set
			{
				if ((this._Tenduan != value))
				{
					this.OnTenduanChanging(value);
					this.SendPropertyChanging();
					this._Tenduan = value;
					this.SendPropertyChanged("Tenduan");
					this.OnTenduanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Int")]
		public System.Nullable<int> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giathue", DbType="Int")]
		public System.Nullable<int> Giathue
		{
			get
			{
				return this._Giathue;
			}
			set
			{
				if ((this._Giathue != value))
				{
					this.OnGiathueChanging(value);
					this.SendPropertyChanging();
					this._Giathue = value;
					this.SendPropertyChanged("Giathue");
					this.OnGiathueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAN1_House", Storage="_Houses", ThisKey="IDDuAn", OtherKey="idduan")]
		public EntitySet<House> Houses
		{
			get
			{
				return this._Houses;
			}
			set
			{
				this._Houses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAN1_Imageduan", Storage="_Imageduans", ThisKey="IDDuAn", OtherKey="IDDuAn")]
		public EntitySet<Imageduan> Imageduans
		{
			get
			{
				return this._Imageduans;
			}
			set
			{
				this._Imageduans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhadautu_DuAN1", Storage="_Nhadautu", ThisKey="IDnhadautu", OtherKey="idnhadautu", IsForeignKey=true)]
		public Nhadautu Nhadautu
		{
			get
			{
				return this._Nhadautu.Entity;
			}
			set
			{
				Nhadautu previousValue = this._Nhadautu.Entity;
				if (((previousValue != value) 
							|| (this._Nhadautu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhadautu.Entity = null;
						previousValue.DuAN1s.Remove(this);
					}
					this._Nhadautu.Entity = value;
					if ((value != null))
					{
						value.DuAN1s.Add(this);
						this._IDnhadautu = value.idnhadautu;
					}
					else
					{
						this._IDnhadautu = default(Nullable<int>);
					}
					this.SendPropertyChanged("Nhadautu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Houses(House entity)
		{
			this.SendPropertyChanging();
			entity.DuAN1 = this;
		}
		
		private void detach_Houses(House entity)
		{
			this.SendPropertyChanging();
			entity.DuAN1 = null;
		}
		
		private void attach_Imageduans(Imageduan entity)
		{
			this.SendPropertyChanging();
			entity.DuAN1 = this;
		}
		
		private void detach_Imageduans(Imageduan entity)
		{
			this.SendPropertyChanging();
			entity.DuAN1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.House")]
	public partial class House : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDHouse;
		
		private string _Tennhadat;
		
		private string _Hinh;
		
		private System.Nullable<int> _GiaBan;
		
		private string _Tenduan;
		
		private string _Gioithieu;
		
		private System.Nullable<int> _Sophong;
		
		private System.Nullable<int> _Dientich;
		
		private string _Vitri;
		
		private System.Nullable<int> _Giathue;
		
		private System.Nullable<int> _idduan;
		
		private System.Nullable<int> _idtaikhoan;
		
		private EntityRef<Imagehouse> _Imagehouse;
		
		private EntityRef<DuAN1> _DuAN1;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHouseChanging(int value);
    partial void OnIDHouseChanged();
    partial void OnTennhadatChanging(string value);
    partial void OnTennhadatChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnGiaBanChanging(System.Nullable<int> value);
    partial void OnGiaBanChanged();
    partial void OnTenduanChanging(string value);
    partial void OnTenduanChanged();
    partial void OnGioithieuChanging(string value);
    partial void OnGioithieuChanged();
    partial void OnSophongChanging(System.Nullable<int> value);
    partial void OnSophongChanged();
    partial void OnDientichChanging(System.Nullable<int> value);
    partial void OnDientichChanged();
    partial void OnVitriChanging(string value);
    partial void OnVitriChanged();
    partial void OnGiathueChanging(System.Nullable<int> value);
    partial void OnGiathueChanged();
    partial void OnidduanChanging(System.Nullable<int> value);
    partial void OnidduanChanged();
    partial void OnidtaikhoanChanging(System.Nullable<int> value);
    partial void OnidtaikhoanChanged();
    #endregion
		
		public House()
		{
			this._Imagehouse = default(EntityRef<Imagehouse>);
			this._DuAN1 = default(EntityRef<DuAN1>);
			this._Taikhoan = default(EntityRef<Taikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHouse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDHouse
		{
			get
			{
				return this._IDHouse;
			}
			set
			{
				if ((this._IDHouse != value))
				{
					this.OnIDHouseChanging(value);
					this.SendPropertyChanging();
					this._IDHouse = value;
					this.SendPropertyChanged("IDHouse");
					this.OnIDHouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhadat", DbType="NVarChar(100)")]
		public string Tennhadat
		{
			get
			{
				return this._Tennhadat;
			}
			set
			{
				if ((this._Tennhadat != value))
				{
					this.OnTennhadatChanging(value);
					this.SendPropertyChanging();
					this._Tennhadat = value;
					this.SendPropertyChanged("Tennhadat");
					this.OnTennhadatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(500)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="Int")]
		public System.Nullable<int> GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this.OnGiaBanChanging(value);
					this.SendPropertyChanging();
					this._GiaBan = value;
					this.SendPropertyChanged("GiaBan");
					this.OnGiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenduan", DbType="NVarChar(100)")]
		public string Tenduan
		{
			get
			{
				return this._Tenduan;
			}
			set
			{
				if ((this._Tenduan != value))
				{
					this.OnTenduanChanging(value);
					this.SendPropertyChanging();
					this._Tenduan = value;
					this.SendPropertyChanged("Tenduan");
					this.OnTenduanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioithieu", DbType="NVarChar(1000)")]
		public string Gioithieu
		{
			get
			{
				return this._Gioithieu;
			}
			set
			{
				if ((this._Gioithieu != value))
				{
					this.OnGioithieuChanging(value);
					this.SendPropertyChanging();
					this._Gioithieu = value;
					this.SendPropertyChanged("Gioithieu");
					this.OnGioithieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sophong", DbType="Int")]
		public System.Nullable<int> Sophong
		{
			get
			{
				return this._Sophong;
			}
			set
			{
				if ((this._Sophong != value))
				{
					this.OnSophongChanging(value);
					this.SendPropertyChanging();
					this._Sophong = value;
					this.SendPropertyChanged("Sophong");
					this.OnSophongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dientich", DbType="Int")]
		public System.Nullable<int> Dientich
		{
			get
			{
				return this._Dientich;
			}
			set
			{
				if ((this._Dientich != value))
				{
					this.OnDientichChanging(value);
					this.SendPropertyChanging();
					this._Dientich = value;
					this.SendPropertyChanged("Dientich");
					this.OnDientichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri", DbType="NVarChar(50)")]
		public string Vitri
		{
			get
			{
				return this._Vitri;
			}
			set
			{
				if ((this._Vitri != value))
				{
					this.OnVitriChanging(value);
					this.SendPropertyChanging();
					this._Vitri = value;
					this.SendPropertyChanged("Vitri");
					this.OnVitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giathue", DbType="Int")]
		public System.Nullable<int> Giathue
		{
			get
			{
				return this._Giathue;
			}
			set
			{
				if ((this._Giathue != value))
				{
					this.OnGiathueChanging(value);
					this.SendPropertyChanging();
					this._Giathue = value;
					this.SendPropertyChanged("Giathue");
					this.OnGiathueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idduan", DbType="Int")]
		public System.Nullable<int> idduan
		{
			get
			{
				return this._idduan;
			}
			set
			{
				if ((this._idduan != value))
				{
					if (this._DuAN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidduanChanging(value);
					this.SendPropertyChanging();
					this._idduan = value;
					this.SendPropertyChanged("idduan");
					this.OnidduanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtaikhoan", DbType="Int")]
		public System.Nullable<int> idtaikhoan
		{
			get
			{
				return this._idtaikhoan;
			}
			set
			{
				if ((this._idtaikhoan != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtaikhoanChanging(value);
					this.SendPropertyChanging();
					this._idtaikhoan = value;
					this.SendPropertyChanged("idtaikhoan");
					this.OnidtaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="House_Imagehouse", Storage="_Imagehouse", ThisKey="IDHouse", OtherKey="IDimageshouse", IsUnique=true, IsForeignKey=false)]
		public Imagehouse Imagehouse
		{
			get
			{
				return this._Imagehouse.Entity;
			}
			set
			{
				Imagehouse previousValue = this._Imagehouse.Entity;
				if (((previousValue != value) 
							|| (this._Imagehouse.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Imagehouse.Entity = null;
						previousValue.House = null;
					}
					this._Imagehouse.Entity = value;
					if ((value != null))
					{
						value.House = this;
					}
					this.SendPropertyChanged("Imagehouse");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAN1_House", Storage="_DuAN1", ThisKey="idduan", OtherKey="IDDuAn", IsForeignKey=true)]
		public DuAN1 DuAN1
		{
			get
			{
				return this._DuAN1.Entity;
			}
			set
			{
				DuAN1 previousValue = this._DuAN1.Entity;
				if (((previousValue != value) 
							|| (this._DuAN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAN1.Entity = null;
						previousValue.Houses.Remove(this);
					}
					this._DuAN1.Entity = value;
					if ((value != null))
					{
						value.Houses.Add(this);
						this._idduan = value.IDDuAn;
					}
					else
					{
						this._idduan = default(Nullable<int>);
					}
					this.SendPropertyChanged("DuAN1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_House", Storage="_Taikhoan", ThisKey="idtaikhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.Houses.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.Houses.Add(this);
						this._idtaikhoan = value.IDTaiKhoan;
					}
					else
					{
						this._idtaikhoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imageduan")]
	public partial class Imageduan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDImageDuAn;
		
		private System.Nullable<int> _IDDuAn;
		
		private string _Link;
		
		private EntityRef<DuAN1> _DuAN1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDImageDuAnChanging(int value);
    partial void OnIDImageDuAnChanged();
    partial void OnIDDuAnChanging(System.Nullable<int> value);
    partial void OnIDDuAnChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    #endregion
		
		public Imageduan()
		{
			this._DuAN1 = default(EntityRef<DuAN1>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDImageDuAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDImageDuAn
		{
			get
			{
				return this._IDImageDuAn;
			}
			set
			{
				if ((this._IDImageDuAn != value))
				{
					this.OnIDImageDuAnChanging(value);
					this.SendPropertyChanging();
					this._IDImageDuAn = value;
					this.SendPropertyChanged("IDImageDuAn");
					this.OnIDImageDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDuAn", DbType="Int")]
		public System.Nullable<int> IDDuAn
		{
			get
			{
				return this._IDDuAn;
			}
			set
			{
				if ((this._IDDuAn != value))
				{
					if (this._DuAN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDDuAnChanging(value);
					this.SendPropertyChanging();
					this._IDDuAn = value;
					this.SendPropertyChanged("IDDuAn");
					this.OnIDDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(500)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DuAN1_Imageduan", Storage="_DuAN1", ThisKey="IDDuAn", OtherKey="IDDuAn", IsForeignKey=true)]
		public DuAN1 DuAN1
		{
			get
			{
				return this._DuAN1.Entity;
			}
			set
			{
				DuAN1 previousValue = this._DuAN1.Entity;
				if (((previousValue != value) 
							|| (this._DuAN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DuAN1.Entity = null;
						previousValue.Imageduans.Remove(this);
					}
					this._DuAN1.Entity = value;
					if ((value != null))
					{
						value.Imageduans.Add(this);
						this._IDDuAn = value.IDDuAn;
					}
					else
					{
						this._IDDuAn = default(Nullable<int>);
					}
					this.SendPropertyChanged("DuAN1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Imagehouse")]
	public partial class Imagehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDimageshouse;
		
		private string _Link;
		
		private System.Nullable<int> _IDhouse;
		
		private EntityRef<House> _House;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDimageshouseChanging(int value);
    partial void OnIDimageshouseChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnIDhouseChanging(System.Nullable<int> value);
    partial void OnIDhouseChanged();
    #endregion
		
		public Imagehouse()
		{
			this._House = default(EntityRef<House>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDimageshouse", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDimageshouse
		{
			get
			{
				return this._IDimageshouse;
			}
			set
			{
				if ((this._IDimageshouse != value))
				{
					if (this._House.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDimageshouseChanging(value);
					this.SendPropertyChanging();
					this._IDimageshouse = value;
					this.SendPropertyChanged("IDimageshouse");
					this.OnIDimageshouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(500)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDhouse", DbType="Int")]
		public System.Nullable<int> IDhouse
		{
			get
			{
				return this._IDhouse;
			}
			set
			{
				if ((this._IDhouse != value))
				{
					this.OnIDhouseChanging(value);
					this.SendPropertyChanging();
					this._IDhouse = value;
					this.SendPropertyChanged("IDhouse");
					this.OnIDhouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="House_Imagehouse", Storage="_House", ThisKey="IDimageshouse", OtherKey="IDHouse", IsForeignKey=true)]
		public House House
		{
			get
			{
				return this._House.Entity;
			}
			set
			{
				House previousValue = this._House.Entity;
				if (((previousValue != value) 
							|| (this._House.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._House.Entity = null;
						previousValue.Imagehouse = null;
					}
					this._House.Entity = value;
					if ((value != null))
					{
						value.Imagehouse = this;
						this._IDimageshouse = value.IDHouse;
					}
					else
					{
						this._IDimageshouse = default(int);
					}
					this.SendPropertyChanged("House");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhadautu")]
	public partial class Nhadautu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idnhadautu;
		
		private string _Tennhadautu;
		
		private string _hinhanh;
		
		private string _mota;
		
		private System.Nullable<int> _sdt;
		
		private string _email;
		
		private string _diachi;
		
		private System.Nullable<System.DateTime> _ngaydautu;
		
		private EntitySet<DuAN1> _DuAN1s;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidnhadautuChanging(int value);
    partial void OnidnhadautuChanged();
    partial void OnTennhadautuChanging(string value);
    partial void OnTennhadautuChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnsdtChanging(System.Nullable<int> value);
    partial void OnsdtChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnngaydautuChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydautuChanged();
    #endregion
		
		public Nhadautu()
		{
			this._DuAN1s = new EntitySet<DuAN1>(new Action<DuAN1>(this.attach_DuAN1s), new Action<DuAN1>(this.detach_DuAN1s));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idnhadautu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idnhadautu
		{
			get
			{
				return this._idnhadautu;
			}
			set
			{
				if ((this._idnhadautu != value))
				{
					this.OnidnhadautuChanging(value);
					this.SendPropertyChanging();
					this._idnhadautu = value;
					this.SendPropertyChanged("idnhadautu");
					this.OnidnhadautuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tennhadautu", DbType="NVarChar(50)")]
		public string Tennhadautu
		{
			get
			{
				return this._Tennhadautu;
			}
			set
			{
				if ((this._Tennhadautu != value))
				{
					this.OnTennhadautuChanging(value);
					this.SendPropertyChanging();
					this._Tennhadautu = value;
					this.SendPropertyChanged("Tennhadautu");
					this.OnTennhadautuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(500)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(500)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="Int")]
		public System.Nullable<int> sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydautu", DbType="Date")]
		public System.Nullable<System.DateTime> ngaydautu
		{
			get
			{
				return this._ngaydautu;
			}
			set
			{
				if ((this._ngaydautu != value))
				{
					this.OnngaydautuChanging(value);
					this.SendPropertyChanging();
					this._ngaydautu = value;
					this.SendPropertyChanged("ngaydautu");
					this.OnngaydautuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhadautu_DuAN1", Storage="_DuAN1s", ThisKey="idnhadautu", OtherKey="IDnhadautu")]
		public EntitySet<DuAN1> DuAN1s
		{
			get
			{
				return this._DuAN1s;
			}
			set
			{
				this._DuAN1s.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DuAN1s(DuAN1 entity)
		{
			this.SendPropertyChanging();
			entity.Nhadautu = this;
		}
		
		private void detach_DuAN1s(DuAN1 entity)
		{
			this.SendPropertyChanging();
			entity.Nhadautu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Taikhoan")]
	public partial class Taikhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTaiKhoan;
		
		private string _Username;
		
		private string _Password;
		
		private string _FullName;
		
		private string _ngaysinh;
		
		private string _Phone;
		
		private string _Email;
		
		private string _mota;
		
		private EntitySet<House> _Houses;
		
		private EntitySet<Tintuc> _Tintucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTaiKhoanChanging(int value);
    partial void OnIDTaiKhoanChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    #endregion
		
		public Taikhoan()
		{
			this._Houses = new EntitySet<House>(new Action<House>(this.attach_Houses), new Action<House>(this.detach_Houses));
			this._Tintucs = new EntitySet<Tintuc>(new Action<Tintuc>(this.attach_Tintucs), new Action<Tintuc>(this.detach_Tintucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTaiKhoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTaiKhoan
		{
			get
			{
				return this._IDTaiKhoan;
			}
			set
			{
				if ((this._IDTaiKhoan != value))
				{
					this.OnIDTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._IDTaiKhoan = value;
					this.SendPropertyChanged("IDTaiKhoan");
					this.OnIDTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50)")]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="NVarChar(50)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(50)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_House", Storage="_Houses", ThisKey="IDTaiKhoan", OtherKey="idtaikhoan")]
		public EntitySet<House> Houses
		{
			get
			{
				return this._Houses;
			}
			set
			{
				this._Houses.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Tintuc", Storage="_Tintucs", ThisKey="IDTaiKhoan", OtherKey="idtaikhoan")]
		public EntitySet<Tintuc> Tintucs
		{
			get
			{
				return this._Tintucs;
			}
			set
			{
				this._Tintucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Houses(House entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_Houses(House entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
		
		private void attach_Tintucs(Tintuc entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = this;
		}
		
		private void detach_Tintucs(Tintuc entity)
		{
			this.SendPropertyChanging();
			entity.Taikhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tintuc")]
	public partial class Tintuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDTinTuc;
		
		private string _tieude;
		
		private System.Nullable<System.DateTime> _thoigiandang;
		
		private string _dangboi;
		
		private string _noidung;
		
		private string _hinhanh;
		
		private string _vitri;
		
		private System.Nullable<int> _idtaikhoan;
		
		private EntityRef<Taikhoan> _Taikhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTinTucChanging(int value);
    partial void OnIDTinTucChanged();
    partial void OntieudeChanging(string value);
    partial void OntieudeChanged();
    partial void OnthoigiandangChanging(System.Nullable<System.DateTime> value);
    partial void OnthoigiandangChanged();
    partial void OndangboiChanging(string value);
    partial void OndangboiChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnhinhanhChanging(string value);
    partial void OnhinhanhChanged();
    partial void OnvitriChanging(string value);
    partial void OnvitriChanged();
    partial void OnidtaikhoanChanging(System.Nullable<int> value);
    partial void OnidtaikhoanChanged();
    #endregion
		
		public Tintuc()
		{
			this._Taikhoan = default(EntityRef<Taikhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTinTuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDTinTuc
		{
			get
			{
				return this._IDTinTuc;
			}
			set
			{
				if ((this._IDTinTuc != value))
				{
					this.OnIDTinTucChanging(value);
					this.SendPropertyChanging();
					this._IDTinTuc = value;
					this.SendPropertyChanged("IDTinTuc");
					this.OnIDTinTucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(50)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this.OntieudeChanging(value);
					this.SendPropertyChanging();
					this._tieude = value;
					this.SendPropertyChanged("tieude");
					this.OntieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoigiandang", DbType="DateTime")]
		public System.Nullable<System.DateTime> thoigiandang
		{
			get
			{
				return this._thoigiandang;
			}
			set
			{
				if ((this._thoigiandang != value))
				{
					this.OnthoigiandangChanging(value);
					this.SendPropertyChanging();
					this._thoigiandang = value;
					this.SendPropertyChanged("thoigiandang");
					this.OnthoigiandangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dangboi", DbType="NVarChar(50)")]
		public string dangboi
		{
			get
			{
				return this._dangboi;
			}
			set
			{
				if ((this._dangboi != value))
				{
					this.OndangboiChanging(value);
					this.SendPropertyChanging();
					this._dangboi = value;
					this.SendPropertyChanged("dangboi");
					this.OndangboiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(500)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hinhanh", DbType="NVarChar(500)")]
		public string hinhanh
		{
			get
			{
				return this._hinhanh;
			}
			set
			{
				if ((this._hinhanh != value))
				{
					this.OnhinhanhChanging(value);
					this.SendPropertyChanging();
					this._hinhanh = value;
					this.SendPropertyChanged("hinhanh");
					this.OnhinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vitri", DbType="NVarChar(50)")]
		public string vitri
		{
			get
			{
				return this._vitri;
			}
			set
			{
				if ((this._vitri != value))
				{
					this.OnvitriChanging(value);
					this.SendPropertyChanging();
					this._vitri = value;
					this.SendPropertyChanged("vitri");
					this.OnvitriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idtaikhoan", DbType="Int")]
		public System.Nullable<int> idtaikhoan
		{
			get
			{
				return this._idtaikhoan;
			}
			set
			{
				if ((this._idtaikhoan != value))
				{
					if (this._Taikhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidtaikhoanChanging(value);
					this.SendPropertyChanging();
					this._idtaikhoan = value;
					this.SendPropertyChanged("idtaikhoan");
					this.OnidtaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Taikhoan_Tintuc", Storage="_Taikhoan", ThisKey="idtaikhoan", OtherKey="IDTaiKhoan", IsForeignKey=true)]
		public Taikhoan Taikhoan
		{
			get
			{
				return this._Taikhoan.Entity;
			}
			set
			{
				Taikhoan previousValue = this._Taikhoan.Entity;
				if (((previousValue != value) 
							|| (this._Taikhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Taikhoan.Entity = null;
						previousValue.Tintucs.Remove(this);
					}
					this._Taikhoan.Entity = value;
					if ((value != null))
					{
						value.Tintucs.Add(this);
						this._idtaikhoan = value.IDTaiKhoan;
					}
					else
					{
						this._idtaikhoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("Taikhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
